import React, { useEffect, useRef } from 'react';
import { Activity, ArrowUpRight, ChevronRight, X, Search, Sparkles, ShieldCheck, Lightbulb, Check, ExternalLink, Database, CreditCard, Server, LockKeyhole, Globe, CircleHelp } from 'lucide-react';
import { AreaChart, Area, CartesianGrid, XAxis, YAxis, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, BarChart, Bar } from 'recharts';
import { historicalMatches, GENERAL_STEPS, SEVERITY } from './engine.js';

export const formatNumber = n => new Intl.NumberFormat('en-IN').format(n);
export const time = t => new Date(t).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false });
export const dateTime = t => new Date(t).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
export const date = t => new Date(t).toLocaleDateString([], { year: 'numeric', month: 'short', day: 'numeric' });
export const kindIcons = { database: Database, payment: CreditCard, authentication: LockKeyhole, network: Globe, api: Server, other: CircleHelp };
export function Logo({ small = false }) { return <div className="brand"><span className="brand-mark"><Activity size={small ? 20 : 25}/></span><span>LogMind <b>AI</b></span></div>; }
export function Badge({ value }) { return <span className={`badge ${String(value).toLowerCase().replace(/\s/g, '-')}`}><i/>{value}</span>; }
export function Empty({ title = 'No results found', text = 'Try adjusting your filters.' }) { return <div className="empty"><Search size={28}/><h3>{title}</h3><p>{text}</p></div>; }
export function Panel({ title, subtitle, action, children, className = '' }) { return <section className={`panel ${className}`}><div className="panel-heading"><div><h3>{title}</h3>{subtitle && <p>{subtitle}</p>}</div>{action}</div>{children}</section>; }
export function Stat({ label, value, icon: Icon, detail, tone = 'purple', onClick }) { return <button className={`stat ${tone}`} onClick={onClick}><span className="stat-top">{label}<Icon size={17}/></span><strong>{formatNumber(value)}</strong><span className="stat-bottom">{detail}<ArrowUpRight size={14}/></span></button>; }
export function Modal({ title, onClose, children }) {
  const ref = useRef(null);
  useEffect(() => { const el = ref.current; el.showModal(); return () => el.close(); }, []);
  return <dialog ref={ref} onCancel={onClose} onClick={e => { if (e.target === e.currentTarget) onClose(); }}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</dialog>;
}
export function SearchBox({ value, onChange, placeholder = 'Search…', className = '' }) { return <label className={`search-box ${className}`}><Search size={17}/><input aria-label={placeholder} value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder}/>{value && <button className="icon-button" aria-label="Clear search" onClick={() => onChange('')}><X size={14}/></button>}</label>; }
export function FrequencyChart({ logs, onSelect }) {
  const end = Math.max(Date.now(), ...logs.map(l => l.timestamp));
  const start = logs.length ? Math.min(...logs.map(l => l.timestamp)) : end - 24 * 3600000;
  const width = Math.max(60000, (end - start + 1) / 12);
  const data = Array.from({ length: 12 }, (_, i) => ({ time: new Date(start + i * width).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: false }), Errors: 0, Warnings: 0 }));
  logs.forEach(l => { const bucket = data[Math.min(11, Math.floor((l.timestamp - start) / width))]; if (bucket) { if (SEVERITY[l.severity] >= 4) bucket.Errors++; else if (l.severity === 'WARNING') bucket.Warnings++; } });
  return <div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} onClick={onSelect} margin={{ top: 12, right: 10, left: -26, bottom: 0 }}><defs><linearGradient id="purple-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#9273ff" stopOpacity={0.32}/><stop offset="100%" stopColor="#9273ff" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#252d43" strokeDasharray="3 5"/><XAxis dataKey="time" tick={{ fill: '#8590ab', fontSize: 10 }} axisLine={false} tickLine={false} minTickGap={28}/><YAxis tick={{ fill: '#8590ab', fontSize: 10 }} allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ background: '#161e31', border: '1px solid #36405d', borderRadius: 10, color: '#fff' }}/><Area type="monotone" dataKey="Errors" stroke="#a18aff" strokeWidth={2.5} fill="url(#purple-area)"/><Area type="monotone" dataKey="Warnings" stroke="#4fd9dc" strokeWidth={1.8} fill="transparent"/></AreaChart></ResponsiveContainer></div>;
}
export function SeverityChart({ logs, onSelect }) {
  const colors = ['#fa7185', '#ffad66', '#ead16f', '#63d5de', '#917aff'];
  const data = Object.keys(SEVERITY).map((name, i) => ({ name, value: logs.filter(l => l.severity === name).length, color: colors[i] })).filter(d => d.value);
  return <div className="donut-wrap"><div className="donut"><ResponsiveContainer width="100%" height={180}><PieChart><Pie data={data} dataKey="value" innerRadius={57} outerRadius={76} paddingAngle={5} stroke="none" onClick={d => onSelect?.(d.name)}>{data.map(d => <Cell key={d.name} fill={d.color} cursor="pointer"/>)}</Pie><Tooltip contentStyle={{ background: '#161e31', borderColor: '#36405d', borderRadius: 10 }} itemStyle={{ color: '#fff' }}/></PieChart></ResponsiveContainer><div className="donut-center"><strong>{formatNumber(logs.length)}</strong><small>log entries</small></div></div><div className="chart-legend">{data.map(d => <button key={d.name} onClick={() => onSelect?.(d.name)}><i style={{ background: d.color }}/><span>{d.name.toLowerCase()}</span><b>{d.value}</b></button>)}</div></div>;
}
export function ServiceChart({ logs, onSelect }) {
  const data = [...new Set(logs.map(l => l.service))].map(service => ({ service, errors: logs.filter(l => l.service === service && SEVERITY[l.severity] >= 4).length })).sort((a,b) => b.errors - a.errors);
  return <div className="chart service-chart"><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={data} margin={{ left: 0, right: 20 }}><XAxis type="number" hide/><YAxis dataKey="service" type="category" width={108} tick={{ fill: '#9ba6be', fontSize: 10 }} axisLine={false} tickLine={false}/><Tooltip cursor={{ fill: '#ffffff05' }} contentStyle={{ background: '#161e31', borderColor: '#36405d', borderRadius: 10 }}/><Bar dataKey="errors" fill="#8970e6" radius={[0, 5, 5, 0]} barSize={12} onClick={d => onSelect?.(d.service)} cursor="pointer"/></BarChart></ResponsiveContainer></div>;
}
export function IncidentList({ incidents, onOpen, compact = false }) {
  if (!incidents.length) return <Empty title="All clear" text="No incidents match this view."/>;
  return <div className="incident-list">{incidents.map(i => { const Icon = kindIcons[i.kind]; return <button key={i.id} className="incident-row" onClick={() => onOpen(i.id)}><span className={`incident-icon ${i.priority.toLowerCase()}`}><Icon size={19}/></span><span className="incident-info"><strong>{i.title}</strong><small>{i.services.join(', ')} <span>·</span> {i.logs.length} events <span>·</span> {dateTime(i.last)}</small></span><span className="incident-right"><Badge value={i.priority}/>{!compact && <Badge value={i.status}/>}<span className="score">{i.score}<small>/100</small></span><ChevronRight size={16}/></span></button>; })}</div>;
}
export function SolutionPanel({ incident, history, feedback, onFeedback, onHistory }) {
  const [expanded, setExpanded] = React.useState(false);
  const matches = historicalMatches(incident, history), match = matches[0];
  const steps = match?.steps || GENERAL_STEPS;
  return <section className="solution-panel"><div className="solution-header"><span className="solution-symbol"><Lightbulb size={21}/></span><div><span className="eyebrow">AI SUGGESTED SOLUTIONS</span><h3>{match ? 'A past resolution may help here' : 'Start with an evidence-led investigation'}</h3></div><span className="method-pill">Rule-based demo</span></div>{match ? <><p><b>Possible cause:</b> {match.rootCause}</p><p><b>Recommended action:</b> {match.steps[0]}</p><div className="match-evidence"><ShieldCheck size={17}/><span><b>{match.score}% match score</b> · {match.id} · {match.sameService ? 'same service' : 'different service'}<small>70% message similarity + 20% service match + 10% error type. A retrieval score, not a probability that the fix will work.</small></span></div><p className="fine">Historical evidence: “{match.messages[0]}”. Current evidence: “{incident.logs[0].message}”. The previous case had a confirmed cause; the current cause remains a hypothesis.</p></> : <p>No reliable historical match found. Here are general investigation steps based on the available logs.</p>}<div className="button-row"><button className="button green" onClick={() => setExpanded(!expanded)}><Sparkles size={15}/>{expanded ? 'Hide possible solutions' : 'Show Possible Solutions'}</button>{match && <button className="button subtle" onClick={() => onHistory(match)}>View Historical Match<ExternalLink size={14}/></button>}<button className={`button subtle ${feedback ? 'selected' : ''}`} onClick={() => onFeedback(incident.id, match?.id)} disabled={!!feedback}><Check size={15}/>{feedback ? 'Feedback recorded' : 'Mark Solution as Helpful'}</button></div>{expanded && <div className="expanded-steps"><h4>{match ? 'Historical resolution · review before applying' : 'General investigation steps'}</h4>{steps.map((step, i) => <label key={step}><input type="checkbox"/>{i + 1}. {step}</label>)}<p className="fine">Validate these steps against the current environment. No changes are applied automatically.</p></div>}</section>;
}
export function HistoricalDetail({ item }) { return <div className="historical-detail"><div className="button-row"><Badge value={item.severity}/><Badge value={item.status}/><span className="muted">{item.id}</span></div><p>{item.service} · {dateTime(item.first)} → {dateTime(item.last)}</p><h4>Original symptoms</h4>{item.messages.map((m,i) => <pre key={i}>{m}</pre>)}<h4>Confirmed root cause · recorded by {item.engineer}</h4><p>{item.rootCause}</p><h4>Documented resolution</h4><ol>{item.steps.map((s,i) => <li key={i}>{s}</li>)}</ol><h4>Unsuccessful investigation</h4><p>{item.failed || 'No unsuccessful fixes documented.'}</p><h4>Outcome</h4><p>{item.outcome}</p><p className="fine">This record belongs to the current demo organization.</p></div>; }
